# Database configuration
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:module1}?currentSchema=public
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}
spring.flyway.enabled=${SPRING_FLYWAY_ENABLED:true}
spring.flyway.baseline-on-migrate=true

# Server configuration
server.port=${MAIN_SERVICE_PORT:8081}

# Swagger/OpenAPI configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui/index.html

# Observability
statistics.observability=${STATISTICS_OBSERVABILITY:true}
observability.intervals=${OBSERVABILITY_INTERVALS:10,30,60}
service.statistic.observability.delay=${SERVICE_STATISTIC_OBSERVABILITY_DELAY:5000}

# Kafka configuration
kafka.hosts=${KAFKA_HOSTS:10.60.3.27:9094,10.60.3.28:9094}
kafka.groupId=${KAFKA_GROUP_ID:ivas-consumer-group}
kafka.topic=${KAFKA_TOPIC:var02_}
kafka.concurrency=${KAFKA_CONCURRENCY:2}