apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-service
  labels:
    app: main-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main-service
  template:
    metadata:
      labels:
        app: main-service
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: main-service
          image: iraavas/12main-service:latest
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: apps-config
            - secretRef:
                name: db-credentials
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
            - name: DB_HOST
              value: "10.60.3.26"
            - name: KAFKA_HOSTS
              value: "10.60.3.27,10.60.3.28"
          resources:
            limits:
              cpu: "1"
              memory: "1024Mi"
            requests:
              cpu: "1"
              memory: "1024Mi"